// frontend react/src/components/cart/CartPage/CartPage.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CartLine, cartStateService } from '../../../services/cartStateService';
import { cardService } from '../../../services/cardService';
import Swal from 'sweetalert2';
import './CartPage.css';

export const CartPage: React.FC = () => {
  const [items, setItems] = useState<CartLine[]>(cartStateService.getItems());
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    setItems(cartStateService.getItems());
    const unsubscribe = cartStateService.subscribe(() => {
      setItems(cartStateService.getItems());
    });
    return unsubscribe;
  }, []);

  const updateQuantity = (cardId: string, quantity: number) => {
    if (!Number.isFinite(quantity) || quantity < 1) return;
    cartStateService.updateQuantity(cardId, quantity);
  };

  const remove = (cardId: string) => {
    cartStateService.removeCard(cardId);
  };

  const clear = async () => {
    const result = await Swal.fire({
      title: '¿Estás seguro?',
      text: 'Se eliminarán todas las cartas del carrito',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sí, vaciar carrito',
      cancelButtonText: 'Cancelar'
    });

    if (result.isConfirmed) {
      cartStateService.clear();
      await Swal.fire({
        icon: 'success',
        title: '¡Carrito vaciado!',
        text: 'Se han eliminado todas las cartas del carrito',
        timer: 2000,
        showConfirmButton: false
      });
    }
  };

  const checkout = async () => {
    if (isProcessing) return;

    setIsProcessing(true);
    
    if (items.length === 0) {
      await Swal.fire({
        icon: 'warning',
        title: 'Carrito vacío',
        text: 'No hay cartas en el carrito para procesar',
        confirmButtonText: 'Entendido'
      });
      setIsProcessing(false);
      return;
    }

    try {
      const updates = items.map(item => {
        const nextStock = Math.max(item.card.stock - item.quantity, 0);
        return cardService.updateCard({
          ...item.card,
          stock: nextStock
        });
      });

      await Promise.all(updates);

      await Swal.fire({
        icon: 'success',
        title: '¡Compra completada!',
        text: 'Tu pedido ha sido procesado exitosamente',
        confirmButtonText: 'Continuar'
      });
      cartStateService.clear();
    } catch (error) {
      console.error('Error al actualizar stock:', error);
      await Swal.fire({
        icon: 'error',
        title: 'Error',
        text: 'No se pudo actualizar el stock. Inténtalo de nuevo.',
        confirmButtonText: 'Entendido'
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const total = items.reduce((sum, item) => sum + item.card.price * item.quantity, 0);

  return (
    <div className="container-fluid py-4 cart-container">
      <div className="row">
        <div className="col-12">
          <h2 className="display-5 mb-4 fw-bold text-white">Mi Carrito</h2>
        </div>
      </div>

      {items.length === 0 ? (
        <div className="empty-state text-center py-5">
          <div className="mb-3" style={{ fontSize: '3rem' }}>🛒</div>
          <h3>Tu carrito está vacío</h3>
          <p className="text-light">Añade cartas a tu carrito para comprar</p>
          <Link to="/card/list" className="btn btn-primary">
            Ver catálogo
          </Link>
        </div>
      ) : (
        <div className="row g-4">
          <div className="col-lg-8">
            <div className="cart-items-section">
              {items.map(item => (
                <div key={item.card._id} className="cart-item">
                  <img src={item.card.imageUrl} alt={item.card.name} className="cart-item-image" />
                  <div className="cart-item-details">
                    <h5>{item.card.name}</h5>
                    <p className="text-light">{item.card.collection} • {item.card.condition}</p>
                    <p className="fw-bold">{item.card.price.toFixed(2)}€</p>
                  </div>
                  <div className="cart-item-quantity">
                    <label>Cantidad:</label>
                    <input
                      type="number"
                      min="1"
                      value={item.quantity}
                      onChange={(e) => updateQuantity(item.card._id, Number(e.target.value))}
                      className="form-control"
                    />
                  </div>
                  <div className="cart-item-total">
                    <p className="fw-bold">{(item.card.price * item.quantity).toFixed(2)}€</p>
                  </div>
                  <button
                    className="remove-btn"
                    onClick={() => remove(item.card._id)}
                  >
                    ✕ Eliminar
                  </button>
                </div>
              ))}
            </div>
          </div>

          <div className="col-lg-4">
            <div className="cart-summary">
              <h4 className="mb-3">Resumen del pedido</h4>
              <div className="summary-row">
                <span>Subtotal:</span>
                <span>{total.toFixed(2)}€</span>
              </div>
              <div className="summary-row">
                <span>Artículos:</span>
                <span>{items.length}</span>
              </div>
              <div className="summary-divider"></div>
              <div className="summary-row total-row">
                <span>Total:</span>
                <span>{total.toFixed(2)}€</span>
              </div>
              <button
                className="btn btn-success btn-lg w-100 mt-3"
                onClick={checkout}
                disabled={isProcessing}
              >
                {isProcessing ? 'Procesando...' : 'Proceder al pago'}
              </button>
              <Link to="/card/list" className="btn btn-outline-secondary btn-lg w-100 mt-2">
                Seguir comprando
              </Link>
              <button
                className="btn btn-outline-danger btn-lg w-100 mt-2"
                onClick={clear}
              >
                Vaciar carrito
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// frontend angular/src/app/components/cart/cart-page/cart-page.component.ts
import { Component, inject } from '@angular/core';
import { AsyncPipe, CurrencyPipe } from '@angular/common';
import { CartStateService } from '../../../service/cart-state.service';
import { RouterLink, Router } from '@angular/router';
import { map, firstValueFrom } from 'rxjs';
import { ServiceCardService } from '../../../service/service-card.service';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-cart-page',
  imports: [AsyncPipe, CurrencyPipe, RouterLink],
  templateUrl: './cart-page.component.html',
  styleUrl: './cart-page.component.css'
})
export class CartPageComponent {
  private readonly cartState = inject(CartStateService);
  private readonly cardService = inject(ServiceCardService);
  private readonly router = inject(Router);

  readonly items$ = this.cartState.items$;
  readonly total$ = this.cartState.items$.pipe(
    map((items) => items.reduce((sum, item) => sum + item.card.price * item.quantity, 0))
  );

  isProcessing = false;

  updateQuantity(cardId: string, value: string): void {
    const quantity = Number.parseInt(value, 10);
    if (!Number.isFinite(quantity)) {
      return;
    }
    this.cartState.updateQuantity(cardId, quantity);
  }

  remove(cardId: string): void {
    this.cartState.removeCard(cardId);
  }

  clear(): void {
    Swal.fire({
      title: '¿Estás seguro?',
      text: 'Se eliminarán todas las cartas del carrito',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sí, vaciar carrito',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {
        this.cartState.clear();
        Swal.fire({
          icon: 'success',
          title: '¡Carrito vaciado!',
          text: 'Se han eliminado todas las cartas del carrito',
          timer: 2000,
          showConfirmButton: false
        });
      }
    });
  }

  async checkout(): Promise<void> {
    if (this.isProcessing) {
      return;
    }

    this.isProcessing = true;

    try {
      // Obtener los items actuales del carrito
      const items = await firstValueFrom(this.items$);

      if (items.length === 0) {
        await Swal.fire({
          icon: 'warning',
          title: 'Carrito vacío',
          text: 'No hay cartas en el carrito para procesar',
          confirmButtonText: 'Entendido'
        });
        this.isProcessing = false;
        return;
      }

      // Procesar cada item del carrito
      for (const item of items) {
        try {
          // Obtener la carta actual del backend
          const response = await firstValueFrom(this.cardService.getCard(item.card._id));
          const currentCard = response.status;

          // Verificar que hay suficiente stock
          if (currentCard.stock < item.quantity) {
            await Swal.fire({
              icon: 'error',
              title: 'Stock insuficiente',
              text: `No hay suficiente stock de ${currentCard.name}. Stock disponible: ${currentCard.stock}`,
              confirmButtonText: 'Entendido'
            });
            this.isProcessing = false;
            return;
          }

          // Actualizar el stock
          const updatedCard = {
            ...currentCard,
            stock: currentCard.stock - item.quantity
          };

          // Enviar la actualización al backend
          await firstValueFrom(this.cardService.updateCard(updatedCard));
        } catch (error) {
          console.error(`Error al actualizar ${item.card.name}:`, error);
          await Swal.fire({
            icon: 'error',
            title: 'Error al procesar',
            text: `Error al procesar ${item.card.name}. Por favor, inténtalo de nuevo.`,
            confirmButtonText: 'Entendido'
          });
          this.isProcessing = false;
          return;
        }
      }

      // Si todo fue exitoso, vaciar el carrito
      this.cartState.clear();
      await Swal.fire({
        icon: 'success',
        title: '¡Compra realizada con éxito!',
        text: 'El stock ha sido actualizado correctamente',
        confirmButtonText: 'Continuar'
      });
      
      // Redirigir al listado de cartas
      this.router.navigate(['/card/list']);
    } catch (error) {
      console.error('Error en el proceso de checkout:', error);
      await Swal.fire({
        icon: 'error',
        title: 'Error',
        text: 'Hubo un error al procesar tu compra. Por favor, inténtalo de nuevo.',
        confirmButtonText: 'Entendido'
      });
    } finally {
      this.isProcessing = false;
    }
  }
}

<div class="cart-container">
  <div class="container-fluid">
    <!-- Header -->
    <div class="cart-header">
      <h2 class="cart-title">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
        </svg>
        Mi Carrito
      </h2>
      <button class="btn btn-outline-danger" type="button" (click)="clear()">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash me-1" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
        </svg>
        Vaciar
      </button>
    </div>

    @if ((items$ | async)?.length === 0) {
      <!-- Empty Cart State -->
      <div class="empty-cart-message">
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-cart-x mb-3" viewBox="0 0 16 16">
          <path d="M7.354 5.646a.5.5 0 1 0-.708.708L7.793 7.5 6.646 8.646a.5.5 0 1 0 .708.708L8.5 8.207l1.146 1.147a.5.5 0 0 0 .708-.708L9.207 7.5l1.147-1.146a.5.5 0 0 0-.708-.708L8.5 6.793z"/>
          <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
        </svg>
        <h4>Tu carrito está vacío</h4>
        <p>Añade cartas desde el catálogo para empezar tu colección</p>
        <button class="btn btn-primary btn-lg mt-2" routerLink="/card/list">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left me-2" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
          </svg>
          Ver catálogo
        </button>
      </div>
    } @else {
      <!-- Cart Items -->
      <div class="cart-items">
        @for (item of items$ | async; track item.card._id) {
          <div class="cart-item-card">
            <div class="item-image">
              <img [src]="item.card.imageUrl" [alt]="item.card.name">
            </div>
            
            <div class="item-details">
              <h5 class="item-name">{{ item.card.name }}</h5>
              <div class="item-info">
                <span class="badge bg-secondary">{{ item.card.collection }}</span>
                <span class="badge bg-info">{{ item.card.rarity }}</span>
              </div>
              <div class="item-price-unit">{{ item.card.price | currency:'EUR' }} / unidad</div>
            </div>

            <div class="item-actions">
              <div class="quantity-section">
                <label class="quantity-label">Cantidad</label>
                <input class="quantity-input" type="number" min="1" max="99"
                       [value]="item.quantity" 
                       (change)="updateQuantity(item.card._id, $any($event.target).value)">
              </div>

              <div class="subtotal-section">
                <span class="subtotal-label">Subtotal</span>
                <span class="subtotal-value">{{ (item.card.price * item.quantity) | currency:'EUR' }}</span>
              </div>

              <button class="btn btn-outline-danger btn-sm remove-btn" type="button" (click)="remove(item.card._id)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                  <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z"/>
                </svg>
                Quitar
              </button>
            </div>
          </div>
        }
      </div>

      <!-- Checkout Section -->
      <div class="checkout-section">
        <button class="btn btn-outline-secondary btn-lg" routerLink="/card/list">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left me-2" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
          </svg>
          Seguir comprando
        </button>

        <div class="checkout-box">
          <div class="total-section">
            <span class="total-label">Total a pagar</span>
            <span class="total-value">{{ total$ | async | currency:'EUR' }}</span>
          </div>
          <button class="btn btn-success btn-lg checkout-btn" type="button" (click)="checkout()" [disabled]="isProcessing">
            @if (isProcessing) {
              <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
              Procesando...
            } @else {
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check-circle me-2" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                <path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/>
              </svg>
              Proceder al pago
            }
          </button>
        </div>
      </div>
    }
  </div>
</div>
