// frontend react/src/components/favorites/Favorites.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../../common/interfaces';
import { favoritesService } from '../../services/favoritesService';
import { cartStateService } from '../../services/cartStateService';
import Swal from 'sweetalert2';
import './Favorites.css';

export const Favorites: React.FC = () => {
  const [favorites, setFavorites] = useState<Card[]>(favoritesService.getFavorites());

  useEffect(() => {
    setFavorites(favoritesService.getFavorites());
    const unsubscribe = favoritesService.subscribe(() => {
      setFavorites(favoritesService.getFavorites());
    });
    return unsubscribe;
  }, []);

  const removeFromFavorites = (cardId: string) => {
    favoritesService.removeFromFavorites(cardId);
  };

  const addToCart = (card: Card) => {
    cartStateService.addCard(card);
    Swal.fire({
      icon: 'success',
      title: '¡Añadido al carrito!',
      text: `${card.name} ha sido añadida al carrito`,
      timer: 2000,
      showConfirmButton: false,
      toast: true,
      position: 'top-end'
    });
  };

  const clearAll = async () => {
    const result = await Swal.fire({
      title: '¿Estás seguro?',
      text: 'Se eliminarán todos los favoritos',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sí, eliminar todo',
      cancelButtonText: 'Cancelar'
    });

    if (result.isConfirmed) {
      favoritesService.clear();
      await Swal.fire({
        icon: 'success',
        title: '¡Favoritos eliminados!',
        text: 'Se han eliminado todos los favoritos',
        timer: 2000,
        showConfirmButton: false
      });
    }
  };

  return (
    <div className="container-fluid py-4 favorites-container">
      <div className="d-flex justify-content-between align-items-center flex-wrap p-3">
        <div>
          <h2 className="display-5 mb-0 fw-bold text-white">Mis Favoritos</h2>
          <div className="text-light">Cantidad de favoritos: {favorites.length}</div>
        </div>
        {favorites.length > 0 && (
          <button className="btn btn-danger" onClick={clearAll}>
            Limpiar todos
          </button>
        )}
      </div>

      {favorites.length === 0 ? (
        <div className="empty-state text-center py-5">
          <div className="mb-3" style={{ fontSize: '3rem' }}>🤍</div>
          <h3>No tienes favoritos</h3>
          <p className="text-light">Añade cartas a tus favoritos para verlas aquí</p>
          <Link to="/card/list" className="btn btn-primary">
            Ver catálogo
          </Link>
        </div>
      ) : (
        <div className="favorites-grid p-3">
          {favorites.map(card => (
            <div key={card._id}>
              <Link to={`/card/detail/${card._id}`} className="card-link">
                <div className="card favorite-card">
                  <img src={card.imageUrl} className="card-img-top" alt={card.name} />
                  <div className="card-body">
                    <h5 className="card-title">{card.name}</h5>
                    <p className="card-text text-light">
                      <small>{card.collection} • {card.condition}</small>
                    </p>
                    <div className="d-flex justify-content-between align-items-center">
                      <span className="h5 mb-0">{card.price.toFixed(2)}€</span>
                    </div>
                  </div>
                </div>
              </Link>
              <div className="mt-2 d-flex gap-2">
                <button 
                  className="btn btn-sm btn-primary flex-grow-1"
                  onClick={() => addToCart(card)}
                >
                  🛒 Añadir
                </button>
                <button 
                  className="btn btn-sm btn-outline-danger"
                  onClick={() => removeFromFavorites(card._id)}
                >
                  ✕
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// frontend angular/src/app/components/favorites/favorites.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { FavoritesService } from '../../service/favorites.service';
import { CartStateService } from '../../service/cart-state.service';
import { Card } from '../../common/interface-card';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-favorites',
  standalone: true,
  imports: [CommonModule, RouterLink, CurrencyPipe],
  templateUrl: './favorites.component.html',
  styleUrl: './favorites.component.css'
})
export class FavoritesComponent {
  private readonly favoritesService = inject(FavoritesService);
  private readonly cartState = inject(CartStateService);

  favorites$ = this.favoritesService.favorites$;

  removeFromFavorites(cardId: string): void {
    this.favoritesService.removeFromFavorites(cardId);
  }

  addToCart(card: Card): void {
    this.cartState.addCard(card);
    Swal.fire({
      icon: 'success',
      title: '¡Añadido al carrito!',
      text: `${card.name} ha sido añadida al carrito`,
      timer: 2000,
      showConfirmButton: false,
      toast: true,
      position: 'top-end'
    });
  }

  clearAll(): void {
    Swal.fire({
      title: '¿Estás seguro?',
      text: 'Se eliminarán todos los favoritos',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sí, eliminar todo',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {
        this.favoritesService.clear();
        Swal.fire({
          icon: 'success',
          title: '¡Favoritos eliminados!',
          text: 'Se han eliminado todos los favoritos',
          timer: 2000,
          showConfirmButton: false
        });
      }
    });
  }
}

<div class="favorites-container">
  <div class="container-fluid">
    <!-- Header -->
    <div class="favorites-header">
      <h2 class="favorites-title">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-heart-fill me-2" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
        </svg>
        Mis Favoritos
      </h2>
      @if ((favorites$ | async)?.length! > 0) {
        <button class="btn btn-outline-danger" type="button" (click)="clearAll()">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash me-1" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
          </svg>
          Limpiar todo
        </button>
      }
    </div>

    @if ((favorites$ | async)?.length === 0) {
      <!-- Empty State -->
      <div class="empty-favorites-message">
        <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" fill="currentColor" class="bi bi-heart mb-3" viewBox="0 0 16 16">
          <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
        </svg>
        <h4>No tienes favoritos aún</h4>
        <p>Explora el catálogo y marca tus cartas favoritas para verlas aquí</p>
        <button class="btn btn-primary btn-lg mt-3" routerLink="/card/list">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid-3x3-gap me-2" viewBox="0 0 16 16">
            <path d="M4 2v2H2V2zm1 12v-2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V7a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m5 10v-2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V7a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1M9 2v2H7V2zm5 0v2h-2V2zM4 7v2H2V7zm5 0v2H7V7zm5 0h-2v2h2zM4 12v2H2v-2zm5 0v2H7v-2zm5 0v2h-2v-2z"/>
          </svg>
          Explorar catálogo
        </button>
      </div>
    } @else {
      <!-- Favorites Grid -->
      <div class="favorites-grid">
        @for (card of favorites$ | async; track card._id) {
          <div class="favorite-card">
            <button class="remove-favorite-btn" type="button" (click)="removeFromFavorites(card._id)" [attr.aria-label]="'Eliminar ' + card.name + ' de favoritos'">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
              </svg>
            </button>

            <a [routerLink]="['/card/detail', card._id]" class="card-image-link">
              <img [src]="card.imageUrl" [alt]="card.name" class="favorite-card-image">
            </a>

            <div class="favorite-card-info">
              <h5 class="favorite-card-name">{{ card.name }}</h5>
              <div class="favorite-card-meta">
                <span class="badge bg-secondary">{{ card.collection }}</span>
                <span class="badge bg-info">{{ card.rarity }}</span>
              </div>
              <div class="favorite-card-price">{{ card.price | currency:'EUR' }}</div>
              
              <div class="favorite-card-actions">
                <button class="btn btn-success w-100" type="button" (click)="addToCart(card)">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus me-1" viewBox="0 0 16 16">
                    <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9z"/>
                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                  </svg>
                  Añadir al carrito
                </button>
              </div>
            </div>
          </div>
        }
      </div>
    }
  </div>
</div>
