// frontend angular/src/app/components/card/card-detail/card-detail.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ServiceCardService } from '../../../service/service-card.service';
import { Card } from '../../../common/interface-card';
import { CartStateService } from '../../../service/cart-state.service';
import { FavoritesService } from '../../../service/favorites.service';
import { CommonModule } from '@angular/common';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-card-detail',
  imports: [RouterLink, CommonModule],
  templateUrl: './card-detail.component.html',
  styleUrl: './card-detail.component.css'
})
export class CardDetailComponent implements OnInit {
  private readonly cardService = inject(ServiceCardService);
  private readonly cartState = inject(CartStateService);
  private readonly favoritesService = inject(FavoritesService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  card: Card | null = null;
  loading = true;
  errorMessage = '';
  
  allCards: Card[] = [];
  currentIndex = -1;

  ngOnInit(): void {
    // Cargar todas las cartas primero
    this.cardService.getCards().subscribe({
      next: (data) => {
        this.allCards = data.status;
        this.loadCurrentCard();
      },
      error: () => {
        this.loadCurrentCard();
      }
    });
  }

  private loadCurrentCard(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (!id) {
      this.loading = false;
      this.errorMessage = 'No se encontro la carta solicitada.';
      return;
    }

    this.cardService.getCard(id).subscribe({
      next: (data) => {
        this.card = data.status;
        // Encontrar el índice de la carta actual
        this.currentIndex = this.allCards.findIndex(c => c._id === this.card!._id);
      },
      error: () => {
        this.errorMessage = 'No se pudo cargar la carta.';
      },
      complete: () => {
        this.loading = false;
      }
    });
  }

  addToCart(): void {
    if (!this.card) {
      return;
    }

    this.cartState.addCard(this.card, 1);
    Swal.fire({
      icon: 'success',
      title: '¡Añadido al carrito!',
      text: `${this.card.name} ha sido añadida al carrito`,
      timer: 2000,
      showConfirmButton: false,
      toast: true,
      position: 'top-end'
    });
  }

  toggleFavorite(): void {
    if (!this.card) {
      return;
    }
    this.favoritesService.toggleFavorite(this.card);
  }

  isFavorite(): boolean {
    return this.card ? this.favoritesService.isFavorite(this.card._id) : false;
  }

  goToNext(): void {
    if (this.currentIndex >= 0 && this.currentIndex < this.allCards.length - 1) {
      const nextCard = this.allCards[this.currentIndex + 1];
      this.router.navigate(['/card/detail', nextCard._id]).then(() => {
        this.loading = true;
        this.loadCurrentCard();
      });
    }
  }

  goToPrevious(): void {
    if (this.currentIndex > 0) {
      const prevCard = this.allCards[this.currentIndex - 1];
      this.router.navigate(['/card/detail', prevCard._id]).then(() => {
        this.loading = true;
        this.loadCurrentCard();
      });
    }
  }

  hasNext(): boolean {
    return this.currentIndex >= 0 && this.currentIndex < this.allCards.length - 1;
  }

  hasPrevious(): boolean {
    return this.currentIndex > 0;
  }
}

<div class="container-fluid my-4 detail-container">
  @if (loading) {
    <div class="text-center">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Cargando...</span>
      </div>
    </div>
  } @else if (errorMessage) {
    <div class="alert alert-danger" role="alert">{{ errorMessage }}</div>
  } @else if (card) {
    <!-- Botones de navegación -->
    <div class="d-flex justify-content-between mb-3">
      <button class="btn btn-outline-secondary" (click)="goToPrevious()" [disabled]="!hasPrevious()">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
        </svg>
        Anterior
      </button>
      <button class="btn btn-outline-secondary" (click)="goToNext()" [disabled]="!hasNext()">
        Siguiente
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
        </svg>
      </button>
    </div>

    <div class="row g-4 align-items-start">
      <div class="col-md-5 col-lg-4">
        <img class="detail-image" [src]="card.imageUrl" [alt]="card.name">
      </div>
      <div class="col-md-7 col-lg-8">
        <div class="d-flex justify-content-between align-items-start flex-wrap gap-2">
          <h2 class="display-6 mb-0 fw-bold">{{ card.name }}</h2>
          <span class="badge rarity-badge">{{ card.rarity }}</span>
        </div>
        <p class="text-light mb-3">{{ card.collection }} · {{ card.type }}</p>

        <div class="info-grid">
          <div>
            <div class="label">Precio</div>
            <div class="value">{{ card.price }}</div>
          </div>
          <div>
            <div class="label">Stock</div>
            <div class="value">{{ card.stock }}</div>
          </div>
          <div>
            <div class="label">Idioma</div>
            <div class="value">{{ card.language }}</div>
          </div>
          <div>
            <div class="label">Estado</div>
            <div class="value">{{ card.condition }}</div>
          </div>
        </div>

        <div class="d-flex flex-wrap gap-2 mt-4">
          <button class="btn btn-primary" type="button" (click)="addToCart()">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus me-1" viewBox="0 0 16 16">
              <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9z"/>
              <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
            </svg>
            Agregar al carrito
          </button>
          <button class="btn" 
                  [class.btn-danger]="isFavorite()" 
                  [class.btn-outline-secondary]="!isFavorite()" 
                  type="button" 
                  (click)="toggleFavorite()">
            @if (isFavorite()) {
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill me-1" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
              </svg>
              Quitar de favoritos
            } @else {
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart me-1" viewBox="0 0 16 16">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
              </svg>
              Añadir a favoritos
            }
          </button>
          <button class="btn btn-outline-secondary" routerLink="/card/list">Volver al listado</button>
          <button class="btn btn-outline-dark" routerLink="/card/edit/{{ card._id }}">Editar</button>
        </div>
      </div>
    </div>
  }
</div>

// frontend react/src/components/card/CardDetail/CardDetail.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Card } from '../../../common/interfaces';
import { cardService } from '../../../services/cardService';
import { cartStateService } from '../../../services/cartStateService';
import { favoritesService } from '../../../services/favoritesService';
import Swal from 'sweetalert2';
import './CardDetail.css';

export const CardDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  
  const [card, setCard] = useState<Card | null>(null);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState('');
  const [allCards, setAllCards] = useState<Card[]>([]);
  const [currentIndex, setCurrentIndex] = useState(-1);
  const [isFav, setIsFav] = useState(false);

  useEffect(() => {
    loadCards();
    const unsubscribe = favoritesService.subscribe(() => {
      if (card) {
        setIsFav(favoritesService.isFavorite(card._id));
      }
    });
    return unsubscribe;
  }, []);

  useEffect(() => {
    if (card) {
      setIsFav(favoritesService.isFavorite(card._id));
    }
  }, [card]);

  const loadCards = async () => {
    try {
      const data = await cardService.getCards();
      setAllCards(data.status);
      loadCurrentCard(data.status);
    } catch {
      loadCurrentCard([]);
    }
  };

  const loadCurrentCard = async (cards: Card[]) => {
    if (!id) {
      setLoading(false);
      setErrorMessage('No se encontro la carta solicitada.');
      return;
    }

    try {
      const data = await cardService.getCard(id);
      setCard(data.status);
      const index = cards.findIndex(c => c._id === data.status._id);
      setCurrentIndex(index);
    } catch {
      setErrorMessage('No se pudo cargar la carta.');
    } finally {
      setLoading(false);
    }
  };

  const addToCart = () => {
    if (!card) return;
    
    cartStateService.addCard(card, 1);
    Swal.fire({
      icon: 'success',
      title: '¡Añadido al carrito!',
      text: `${card.name} ha sido añadida al carrito`,
      timer: 2000,
      showConfirmButton: false,
      toast: true,
      position: 'top-end'
    });
  };

  const toggleFavorite = () => {
    if (!card) return;
    favoritesService.toggleFavorite(card);
  };

  const goToPrevious = () => {
    if (currentIndex > 0) {
      const prevCard = allCards[currentIndex - 1];
      navigate(`/card/detail/${prevCard._id}`);
      setLoading(true);
      loadCards();
    }
  };

  const goToNext = () => {
    if (currentIndex >= 0 && currentIndex < allCards.length - 1) {
      const nextCard = allCards[currentIndex + 1];
      navigate(`/card/detail/${nextCard._id}`);
      setLoading(true);
      loadCards();
    }
  };

  const hasPrevious = () => currentIndex > 0;
  const hasNext = () => currentIndex >= 0 && currentIndex < allCards.length - 1;

  if (loading) {
    return (
      <div className="container-fluid my-4 detail-container">
        <div className="text-center">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Cargando...</span>
          </div>
        </div>
      </div>
    );
  }

  if (errorMessage) {
    return (
      <div className="container-fluid my-4">
        <div className="alert alert-danger" role="alert">{errorMessage}</div>
      </div>
    );
  }

  if (!card) {
    return null;
  }

  return (
    <div className="container-fluid my-4 detail-container">
      <div className="d-flex justify-content-between mb-3">
        <button className="btn btn-nav" onClick={goToPrevious} disabled={!hasPrevious()}>
          ← Anterior
        </button>
        <button className="btn btn-nav" onClick={goToNext} disabled={!hasNext()}>
          Siguiente →
        </button>
      </div>

      <div className="row g-4 align-items-start">
        <div className="col-md-5 col-lg-4">
          <img className="detail-image" src={card.imageUrl} alt={card.name} />
        </div>
        <div className="col-md-7 col-lg-8">
          <div className="d-flex justify-content-between align-items-start flex-wrap gap-2">
            <h2 className="display-6 mb-0 fw-bold text-white">{card.name}</h2>
            <span className="badge rarity-badge">{card.rarity}</span>
          </div>
          <p className="text-light mb-3">{card.collection} · {card.type}</p>

          <div className="info-grid">
            <div>
              <div className="label">Precio</div>
              <div className="value">{card.price.toFixed(2)}€</div>
            </div>
            <div>
              <div className="label">Stock</div>
              <div className="value">{card.stock}</div>
            </div>
            <div>
              <div className="label">Idioma</div>
              <div className="value">{card.language}</div>
            </div>
            <div>
              <div className="label">Estado</div>
              <div className="value">{card.condition}</div>
            </div>
          </div>

          <div className="d-flex flex-wrap gap-2 mt-4">
            <button className="btn btn-primary" onClick={addToCart}>
              🛒 Agregar al carrito
            </button>
            <button 
              className={`btn ${isFav ? 'btn-danger' : 'btn-outline-secondary'}`}
              onClick={toggleFavorite}
            >
              {isFav ? '❤️ Quitar de favoritos' : '🤍 Añadir a favoritos'}
            </button>
            <Link to="/card/list" className="btn btn-outline-secondary">Volver al listado</Link>
            <Link to={`/card/edit/${card._id}`} className="btn btn-edit">Editar</Link>
          </div>
        </div>
      </div>
    </div>
  );
};
