// frontend angular/src/app/components/home/home.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ServiceCardService } from '../../service/service-card.service';
import { CartStateService, CartLine } from '../../service/cart-state.service';
import { FavoritesService } from '../../service/favorites.service';
import { Card } from '../../common/interface-card';
import { Observable, map } from 'rxjs';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit {
  private readonly cardService = inject(ServiceCardService);
  private readonly cartState = inject(CartStateService);
  private readonly favoritesService = inject(FavoritesService);

  recentCards: Card[] = [];
  cartItems$ = this.cartState.items$;
  favorites$ = this.favoritesService.favorites$;
  cartItemsCount$ = this.cartState.items$.pipe(
    map((items: CartLine[]) => items.reduce((sum: number, item: CartLine) => sum + item.quantity, 0))
  );
  favoritesCount$ = this.favoritesService.favorites$.pipe(
    map((favs: Card[]) => favs.length)
  );

  ngOnInit(): void {
    this.loadRecentCards();
  }

  loadRecentCards(): void {
    this.cardService.getCards().subscribe({
      next: (response) => {
        // Mostrar solo las primeras 6 cartas
        this.recentCards = response.status.slice(0, 6);
      },
      error: (error) => {
        console.error('Error al cargar cartas:', error);
      }
    });
  }
}

<div class="home-container">
  <div class="container-fluid py-4">
    
    <!-- Hero Section -->
    <div class="hero-section mb-5">
      <div class="row align-items-center">
        <div class="col-lg-8">
          <h1 class="display-3 fw-bold mb-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-card-image me-3" viewBox="0 0 16 16">
              <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
              <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54L1 12.5v-9a.5.5 0 0 1 .5-.5z"/>
            </svg>
            Bienvenido a Mana Market
          </h1>
          <p class="lead text-light-emphasis mb-4">Tu tienda especializada en cartas de Magic: The Gathering. Explora, colecciona y construye tu mazo perfecto.</p>
          <div class="d-flex gap-3 flex-wrap">
            <button routerLink="/card/list" class="btn btn-primary btn-lg px-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid-3x3-gap me-2" viewBox="0 0 16 16">
                <path d="M4 2v2H2V2zm1 12v-2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V7a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m5 10v-2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V7a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1m0-5V2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1M9 2v2H7V2zm5 0v2h-2V2zM4 7v2H2V7zm5 0v2H7V7zm5 0h-2v2h2zM4 12v2H2v-2zm5 0v2H7v-2zm5 0v2h-2v-2z"/>
              </svg>
              Ver todas las cartas
            </button>
            <button routerLink="/favorites" class="btn btn-outline-light btn-lg px-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-heart me-2" viewBox="0 0 16 16">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
              </svg>
              Mis favoritos
            </button>
          </div>
        </div>
        <div class="col-lg-4 text-center mt-4 mt-lg-0">
          <div class="stats-card">
            <div class="stat-item">
              <div class="stat-value">{{ favoritesCount$ | async }}</div>
              <div class="stat-label">Favoritos</div>
            </div>
            <div class="stat-divider"></div>
            <div class="stat-item">
              <div class="stat-value">{{ cartItemsCount$ | async }}</div>
              <div class="stat-label">En el carrito</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Quick Access Sections -->
    <div class="row g-4 mb-5">
      <!-- Cart Preview -->
      <div class="col-md-6">
        <div class="section-card">
          <div class="section-header">
            <h3>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
              </svg>
              Mi Carrito
            </h3>
            <a routerLink="/cart" class="view-all-link">Ver todo →</a>
          </div>
          
          @if ((cartItems$ | async)?.length === 0) {
            <div class="empty-state">
              <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-cart-x mb-2" viewBox="0 0 16 16">
                <path d="M7.354 5.646a.5.5 0 1 0-.708.708L7.793 7.5 6.646 8.646a.5.5 0 1 0 .708.708L8.5 8.207l1.146 1.147a.5.5 0 0 0 .708-.708L9.207 7.5l1.147-1.146a.5.5 0 0 0-.708-.708L8.5 6.793z"/>
                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
              </svg>
              <p>Tu carrito está vacío</p>
            </div>
          } @else {
            <div class="preview-list">
              @for (item of (cartItems$ | async)?.slice(0, 3); track item.card._id) {
                <div class="preview-item">
                  <img [src]="item.card.imageUrl" [alt]="item.card.name" class="preview-image">
                  <div class="preview-info">
                    <div class="preview-name">{{ item.card.name }}</div>
                    <div class="preview-quantity">Cantidad: {{ item.quantity }}</div>
                  </div>
                </div>
              }
              @if ((cartItems$ | async)!.length > 3) {
                <div class="more-items">+ {{ (cartItems$ | async)!.length - 3 }} más</div>
              }
            </div>
          }
        </div>
      </div>

      <!-- Favorites Preview -->
      <div class="col-md-6">
        <div class="section-card">
          <div class="section-header">
            <h3>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart-fill me-2" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
              </svg>
              Mis Favoritos
            </h3>
            <a routerLink="/favorites" class="view-all-link">Ver todo →</a>
          </div>
          
          @if ((favorites$ | async)?.length === 0) {
            <div class="empty-state">
              <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-heart mb-2" viewBox="0 0 16 16">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
              </svg>
              <p>No tienes favoritos aún</p>
            </div>
          } @else {
            <div class="preview-list">
              @for (card of (favorites$ | async)?.slice(0, 3); track card._id) {
                <div class="preview-item">
                  <img [src]="card.imageUrl" [alt]="card.name" class="preview-image">
                  <div class="preview-info">
                    <div class="preview-name">{{ card.name }}</div>
                    <div class="preview-collection">{{ card.collection }}</div>
                  </div>
                </div>
              }
              @if ((favorites$ | async)!.length > 3) {
                <div class="more-items">+ {{ (favorites$ | async)!.length - 3 }} más</div>
              }
            </div>
          }
        </div>
      </div>
    </div>

    <!-- Recent Cards -->
    <div class="section-card">
      <div class="section-header">
        <h3>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-stars me-2" viewBox="0 0 16 16">
            <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.73 1.73 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.73 1.73 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.73 1.73 0 0 0 3.407 2.31zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.16 1.16 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.16 1.16 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732z"/>
          </svg>
          Cartas Destacadas
        </h3>
        <a routerLink="/card/list" class="view-all-link">Ver catálogo completo →</a>
      </div>
      
      <div class="row g-4">
        @for (card of recentCards; track card._id) {
          <div class="col-6 col-sm-4 col-md-3 col-lg-2">
            <a [routerLink]="['/card/detail', card._id]" class="card-preview-link">
              <div class="card-preview">
                <img [src]="card.imageUrl" [alt]="card.name" class="card-preview-image">
                <div class="card-preview-name">{{ card.name }}</div>
              </div>
            </a>
          </div>
        }
      </div>
    </div>
  </div>
</div>

// frontend react/src/components/home/Home.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../../common/interfaces';
import { CartLine as CartLineType } from '../../services/cartStateService';
import { cardService } from '../../services/cardService';
import { cartStateService } from '../../services/cartStateService';
import { favoritesService } from '../../services/favoritesService';
import './Home.css';

export const Home: React.FC = () => {
  const [recentCards, setRecentCards] = useState<Card[]>([]);
  const [cartItems, setCartItems] = useState<CartLineType[]>(cartStateService.getItems());
  const [favorites, setFavorites] = useState<Card[]>(favoritesService.getFavorites());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadRecentCards();
    
    const unsubscribeCart = cartStateService.subscribe(() => {
      setCartItems(cartStateService.getItems());
    });
    
    const unsubscribeFav = favoritesService.subscribe(() => {
      setFavorites(favoritesService.getFavorites());
    });

    return () => {
      unsubscribeCart();
      unsubscribeFav();
    };
  }, []);

  const loadRecentCards = async () => {
    try {
      console.log('Iniciando carga de cartas desde:', 'http://localhost:3000/api/v1/cards/');
      const data = await cardService.getCards();
      console.log('Cartas cargadas:', data);
      setRecentCards(data.status.slice(0, 6));
      setLoading(false);
    } catch (error) {
      console.error('Error al cargar cartas:', error);
      setRecentCards([]);
      setLoading(false);
    }
  };

  const cartItemsCount = cartItems.reduce((sum, item) => sum + item.quantity, 0);
  const favoritesCount = favorites.length;

  return (
    <div className="home-container">
      <div className="container-fluid py-4">
        {/* Hero Section */}
        <div className="hero-section mb-5">
          <div className="row align-items-center">
            <div className="col-lg-8">
              <h1 className="display-3 fw-bold mb-3">
                🎴 Bienvenido a Mana Market
              </h1>
              <p className="lead text-white mb-4">
                Tu tienda especializada en cartas de Magic: The Gathering. Explora, colecciona y construye tu mazo perfecto.
              </p>
              <div className="d-flex gap-3 flex-wrap">
                <Link to="/card/list" className="btn btn-primary btn-lg px-4">
                  📊 Ver todas las cartas
                </Link>
                <Link to="/favorites" className="btn btn-outline-light btn-lg px-4">
                  ❤️ Mis favoritos
                </Link>
              </div>
            </div>
            <div className="col-lg-4 text-center mt-4 mt-lg-0">
              <div className="stats-card">
                <div className="stat-item">
                  <div className="stat-value">{favoritesCount}</div>
                  <div className="stat-label">Favoritos</div>
                </div>
                <div className="stat-divider"></div>
                <div className="stat-item">
                  <div className="stat-value">{cartItemsCount}</div>
                  <div className="stat-label">En el carrito</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Quick Access Sections */}
        <div className="row g-4 mb-5">
          {/* Cart Preview */}
          <div className="col-md-6">
            <div className="section-card">
              <div className="section-header">
                <h3>🛒 Mi Carrito</h3>
                <Link to="/cart" className="view-all-link">Ver todo →</Link>
              </div>
              
              {cartItems.length === 0 ? (
                <div className="empty-state">
                  <div style={{ fontSize: '2rem' }}>🛒</div>
                  <p>Tu carrito está vacío</p>
                </div>
              ) : (
                <div className="preview-list">
                  {cartItems.slice(0, 3).map(item => (
                    <div key={item.card._id} className="preview-item">
                      <img src={item.card.imageUrl} alt={item.card.name} className="preview-image" />
                      <div className="preview-info">
                        <div className="preview-name">{item.card.name}</div>
                        <div className="preview-quantity">Cantidad: {item.quantity}</div>
                      </div>
                    </div>
                  ))}
                  {cartItems.length > 3 && (
                    <div className="more-items">+ {cartItems.length - 3} más</div>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Favorites Preview */}
          <div className="col-md-6">
            <div className="section-card">
              <div className="section-header">
                <h3>❤️ Mis Favoritos</h3>
                <Link to="/favorites" className="view-all-link">Ver todo →</Link>
              </div>
              
              {favorites.length === 0 ? (
                <div className="empty-state">
                  <div style={{ fontSize: '2rem' }}>🤍</div>
                  <p>No tienes favoritos</p>
                </div>
              ) : (
                <div className="preview-list">
                  {favorites.slice(0, 3).map(card => (
                    <Link key={card._id} to={`/card/detail/${card._id}`} className="preview-item">
                      <img src={card.imageUrl} alt={card.name} className="preview-image" />
                      <div className="preview-info">
                        <div className="preview-name">{card.name}</div>
                        <div className="preview-quantity">{card.price.toFixed(2)}€</div>
                      </div>
                    </Link>
                  ))}
                  {favorites.length > 3 && (
                    <div className="more-items">+ {favorites.length - 3} más</div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Recent Cards Section */}
        <div className="recent-cards-section">
          <h3 className="mb-4 fw-bold">📋 Cartas Recientes</h3>
          {loading ? (
            <p>Cargando cartas...</p>
          ) : (
            <div className="carousel-container">
              <div className="carousel-track">
                {recentCards.map(card => (
                  <div key={card._id} className="carousel-card">
                    <Link to={`/card/detail/${card._id}`} className="card-link">
                      <div className="card">
                        <img src={card.imageUrl} className="card-img-top" alt={card.name} />
                        <div className="card-body">
                          <h5 className="card-title text-white">{card.name}</h5>
                          <p className="card-text text-light">
                            <small>{card.collection}</small>
                          </p>
                          <div className="d-flex justify-content-between align-items-center">
                            <span className="h5 mb-0 text-white fw-bold">{card.price.toFixed(2)}€</span>
                          </div>
                        </div>
                      </div>
                    </Link>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
