// frontend react/src/components/card/CardEdit/CardEdit.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { cardService } from '../../../services/cardService';
import Swal from 'sweetalert2';
import './CardEdit.css';

export const CardEdit: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    _id: '',
    name: '',
    collection: '',
    rarity: '',
    type: '',
    price: 0,
    stock: 0,
    language: '',
    condition: '',
    imageUrl: ''
  });

  const [collections, setCollections] = useState<string[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [showNewCollection, setShowNewCollection] = useState(false);
  const [newCollection, setNewCollection] = useState('');

  useEffect(() => {
    loadCollections();
    if (id) {
      loadCard();
    } else {
      setIsEditing(false);
    }
  }, [id]);

  const loadCollections = async () => {
    try {
      const data = await cardService.getCollections();
      setCollections(data.status);
    } catch (error) {
      console.error('Error loading collections:', error);
    }
  };

  const loadCard = async () => {
    try {
      const data = await cardService.getCard(id!);
      setFormData(data.status);
      setIsEditing(true);
    } catch {
      Swal.fire({
        icon: 'error',
        title: 'Error al cargar',
        text: 'No se pudo cargar la información de la carta',
        confirmButtonText: 'Entendido'
      });
    }
  };

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.name || formData.name.length < 2) {
      newErrors.name = 'El nombre debe tener al menos 2 caracteres';
    }
    if (!formData.collection || formData.collection.length < 2) {
      newErrors.collection = 'La colección es requerida';
    }
    if (!formData.rarity || formData.rarity.length < 2) {
      newErrors.rarity = 'La rareza es requerida';
    }
    if (!formData.type || formData.type.length < 2) {
      newErrors.type = 'El tipo es requerido';
    }
    if (formData.price < 0) {
      newErrors.price = 'El precio no puede ser negativo';
    }
    if (formData.stock < 0) {
      newErrors.stock = 'El stock no puede ser negativo';
    }
    if (!formData.language || formData.language.length < 2) {
      newErrors.language = 'El idioma es requerido';
    }
    if (!formData.condition || formData.condition.length < 2) {
      newErrors.condition = 'El estado es requerido';
    }
    if (!formData.imageUrl || formData.imageUrl.length < 5) {
      newErrors.imageUrl = 'La URL de la imagen es requerida';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'price' || name === 'stock' ? Number(value) : value
    }));
  };

  const handleAddCollection = () => {
    if (newCollection.trim() && !collections.includes(newCollection.trim())) {
      const updatedCollections = [...collections, newCollection.trim()].sort();
      setCollections(updatedCollections);
      setFormData(prev => ({
        ...prev,
        collection: newCollection.trim()
      }));
      setNewCollection('');
      setShowNewCollection(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      Swal.fire({
        icon: 'warning',
        title: 'Formulario incompleto',
        text: 'Revisa los campos obligatorios antes de continuar.',
        confirmButtonText: 'Entendido'
      });
      return;
    }

    setIsSubmitting(true);

    try {
      if (isEditing) {
        await cardService.updateCard(formData);
        await Swal.fire({
          icon: 'success',
          title: '¡Carta modificada!',
          text: 'La carta ha sido actualizada correctamente',
          confirmButtonText: 'Continuar'
        });
      } else {
        const { _id, ...createPayload } = formData;
        await cardService.addCard(createPayload);
        await Swal.fire({
          icon: 'success',
          title: '¡Carta creada!',
          text: 'La carta ha sido agregada correctamente',
          confirmButtonText: 'Continuar'
        });
      }
      navigate('/card/list');
    } catch (error) {
      const apiMessage = (error as { response?: { data?: { status?: string } } })?.response?.data?.status;
      console.error('Error guardando carta:', error);
      Swal.fire({
        icon: 'error',
        title: 'Error',
        text: apiMessage ?? (isEditing
          ? 'No se pudo actualizar la carta. Por favor, inténtalo de nuevo.'
          : 'No se pudo crear la carta. Por favor, inténtalo de nuevo.'),
        confirmButtonText: 'Entendido'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDelete = async () => {
    const result = await Swal.fire({
      title: '¿Estás seguro?',
      text: 'Se eliminará la carta de forma permanente',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#d33',
      cancelButtonColor: '#3085d6',
      confirmButtonText: 'Sí, eliminar',
      cancelButtonText: 'Cancelar'
    });

    if (!result.isConfirmed) return;

    setIsSubmitting(true);
    try {
      await cardService.deleteCard(formData._id);
      await Swal.fire({
        icon: 'success',
        title: '¡Eliminada!',
        text: 'La carta ha sido eliminada correctamente',
        confirmButtonText: 'Continuar'
      });
      navigate('/card/list');
    } catch {
      Swal.fire({
        icon: 'error',
        title: 'Error',
        text: 'No se pudo eliminar la carta.',
        confirmButtonText: 'Entendido'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="container-fluid edit-container">
      <div className="row justify-content-center">
        <div className="col-12 col-lg-10 col-xl-8 my-4">
          <div className="card card-custom">
            <div className="card-header text-center bg-mtg-blue text-white">
              <h2 className="mb-0">{isEditing ? 'Editar carta' : 'Nueva carta'}</h2>
            </div>
            <div className="card-body">
              <form onSubmit={handleSubmit} className="card-form">
                <div className="row g-3">
                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="name" className="form-label">Nombre de la carta</label>
                      <input
                        type="text"
                        name="name"
                        className={`form-control ${errors.name ? 'is-invalid' : ''}`}
                        id="name"
                        placeholder="Nombre"
                        value={formData.name}
                        onChange={handleChange}
                      />
                      {errors.name && <div className="invalid-feedback">{errors.name}</div>}
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="collection" className="form-label" id="collection-label">Colección</label>
                      {!showNewCollection ? (
                        <div>
                          <select
                            name="collection"
                            className={`form-select ${errors.collection ? 'is-invalid' : ''}`}
                            id="collection"
                            value={formData.collection}
                            onChange={handleChange}
                          >
                            <option value="">Selecciona una colección</option>
                            {collections.map(collection => (
                              <option key={collection} value={collection}>{collection}</option>
                            ))}
                          </select>
                          <button
                            type="button"
                            className="btn btn-outline-primary btn-sm mt-2 w-100"
                            onClick={() => setShowNewCollection(true)}
                          >
                            + Crear nueva colección
                          </button>
                          {errors.collection && <div className="invalid-feedback">{errors.collection}</div>}
                        </div>
                      ) : (
                        <div>
                          <div className="d-flex gap-2">
                            <input
                              type="text"
                              className="form-control new-collection-input"
                              placeholder="Nombre de la colección"
                              value={newCollection}
                              onChange={(e) => setNewCollection(e.target.value)}
                              onKeyPress={(e) => {
                                if (e.key === 'Enter') {
                                  handleAddCollection();
                                }
                              }}
                            />
                            <button
                              type="button"
                              className="btn btn-success"
                              onClick={handleAddCollection}
                              disabled={!newCollection.trim()}
                            >
                              ✓
                            </button>
                          </div>
                          <button
                            type="button"
                            className="btn btn-outline-secondary btn-sm mt-2 w-100"
                            onClick={() => {
                              setShowNewCollection(false);
                              setNewCollection('');
                            }}
                          >
                            Cancelar
                          </button>
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="rarity" className="form-label">Rareza</label>
                      <input
                        type="text"
                        name="rarity"
                        className={`form-control ${errors.rarity ? 'is-invalid' : ''}`}
                        id="rarity"
                        placeholder="Rareza"
                        value={formData.rarity}
                        onChange={handleChange}
                      />
                      {errors.rarity && <div className="invalid-feedback">{errors.rarity}</div>}
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="type" className="form-label">Tipo de carta</label>
                      <input
                        type="text"
                        name="type"
                        className={`form-control ${errors.type ? 'is-invalid' : ''}`}
                        id="type"
                        placeholder="Tipo"
                        value={formData.type}
                        onChange={handleChange}
                      />
                      {errors.type && <div className="invalid-feedback">{errors.type}</div>}
                    </div>
                  </div>

                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="price" className="form-label">Precio (€)</label>
                      <input
                        type="number"
                        name="price"
                        className={`form-control ${errors.price ? 'is-invalid' : ''}`}
                        id="price"
                        placeholder="0.00"
                        min="0"
                        step="0.01"
                        value={formData.price}
                        onChange={handleChange}
                      />
                      {errors.price && <div className="invalid-feedback">{errors.price}</div>}
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="stock" className="form-label">Stock disponible</label>
                      <input
                        type="number"
                        name="stock"
                        className={`form-control ${errors.stock ? 'is-invalid' : ''}`}
                        id="stock"
                        placeholder="0"
                        min="0"
                        step="1"
                        value={formData.stock}
                        onChange={handleChange}
                      />
                      {errors.stock && <div className="invalid-feedback">{errors.stock}</div>}
                    </div>
                  </div>

                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="language" className="form-label">Idioma</label>
                      <input
                        type="text"
                        name="language"
                        className={`form-control ${errors.language ? 'is-invalid' : ''}`}
                        id="language"
                        placeholder="Idioma"
                        value={formData.language}
                        onChange={handleChange}
                      />
                      {errors.language && <div className="invalid-feedback">{errors.language}</div>}
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="mb-3">
                      <label htmlFor="condition" className="form-label">Estado</label>
                      <input
                        type="text"
                        name="condition"
                        className={`form-control ${errors.condition ? 'is-invalid' : ''}`}
                        id="condition"
                        placeholder="Estado"
                        value={formData.condition}
                        onChange={handleChange}
                      />
                      {errors.condition && <div className="invalid-feedback">{errors.condition}</div>}
                    </div>
                  </div>

                  <div className="col-12">
                    <div className="mb-3">
                      <label htmlFor="imageUrl" className="form-label">URL de la imagen</label>
                      <input
                        type="text"
                        name="imageUrl"
                        className={`form-control ${errors.imageUrl ? 'is-invalid' : ''}`}
                        id="imageUrl"
                        placeholder="https://"
                        value={formData.imageUrl}
                        onChange={handleChange}
                      />
                      {errors.imageUrl && <div className="invalid-feedback">{errors.imageUrl}</div>}
                    </div>
                  </div>
                </div>

                <div className="d-flex justify-content-between mt-4">
                  <div className="d-flex gap-2">
                    <button type="button" className="btn btn-outline-secondary btn-lg px-4" onClick={() => navigate('/card/list')}>Cancelar</button>
                    {isEditing && (
                      <button type="button" className="btn btn-danger btn-lg px-4" onClick={handleDelete} disabled={isSubmitting}>
                        Eliminar
                      </button>
                    )}
                  </div>
                  <button type="submit" className="btn btn-success btn-lg px-5" disabled={isSubmitting}>
                    {isSubmitting ? 'Procesando...' : (isEditing ? 'Actualizar' : 'Crear carta')}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// frontend angular/src/app/components/card/card-edit/card-edit.component.ts
import {Component, inject, Input, OnInit} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators} from '@angular/forms';
import {ServiceCardService} from '../../../service/service-card.service';
import {ActivatedRoute, Router, RouterLink} from '@angular/router';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-card-edit',
  imports: [
    FormsModule,
    ReactiveFormsModule,
    RouterLink
  ],
  templateUrl: './card-edit.component.html',
  styleUrls: ['./card-edit.component.css']
})
export class CardEditComponent implements OnInit{
  @Input("id") id!:string;
  editar = false;
  collectionList: string[] = [];
  isSubmitting = false;

  private readonly formBuilder: FormBuilder = inject(FormBuilder);
  private readonly cardService: ServiceCardService = inject(ServiceCardService);
  private readonly router : Router = inject(Router);
  private readonly route: ActivatedRoute = inject(ActivatedRoute);

  formCard : FormGroup = this.formBuilder.group({
    _id: [],
    name: ['', [Validators.required,
      Validators.minLength(2),
      Validators.maxLength(120)]],
    collection: ['', [Validators.required,
      Validators.minLength(2),
      Validators.maxLength(120)]],
    rarity: ['', [Validators.required,
      Validators.minLength(2),
      Validators.maxLength(50)]],
    type: ['', [Validators.required,
      Validators.minLength(2),
      Validators.maxLength(50)]],
    price: [0, [Validators.required, Validators.min(0)]],
    stock: [0, [Validators.required, Validators.min(0)]],
    language: ['', [Validators.required,
      Validators.minLength(2),
      Validators.maxLength(10)]],
    condition: ['', [Validators.required,
      Validators.minLength(2),
      Validators.maxLength(20)]],
    imageUrl: ['', [Validators.required,
      Validators.minLength(5),
      Validators.maxLength(500)]]
  })

  myNewCollection: FormGroup = this.formBuilder.group({
    newCollection:['']
  });


  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id') ?? '';
    this.loadCard();
  }

  get name():any {
    return this.formCard.get('name');
  }
  get collection():any {
    return this.formCard.get('collection');
  }
  get rarity():any {
    return this.formCard.get('rarity');
  }
  get type():any {
    return this.formCard.get('type');
  }
  get price():any {
    return this.formCard.get('price');
  }
  get stock():any {
    return this.formCard.get('stock');
  }
  get language():any {
    return this.formCard.get('language');
  }
  get condition():any {
    return this.formCard.get('condition');
  }

  get imageUrl():any {
    return this.formCard.get('imageUrl');
  }

  get newCollection():any {
    return this.myNewCollection.get('newCollection');
  }

  private loadCard() {
    if (this.id) {
      this.editar = true;
      this.cardService.getCard(this.id).subscribe({
        next:(data)=>{
          this.formCard.patchValue(data.status)
        },
        error:(err)=>{
          console.error('Error loading card', err);
          Swal.fire({
            icon: 'error',
            title: 'Error al cargar',
            text: 'No se pudo cargar la información de la carta',
            confirmButtonText: 'Entendido'
          });
        },
        complete:()=>{
          console.log('Card loaded successfully');
        }
      })
    }
    else {
      this.formCard.reset({
        price: 0,
        stock: 0
      });
      this.editar = false;
    }
    this.cardService.getCollections().subscribe({
      next:(data)=>{
        this.collectionList = data.status
      }
    })
  }

  addCard() {
    if (this.isSubmitting) {
      return;
    }

    if (this.formCard.invalid) {
      this.formCard.markAllAsTouched();
      Swal.fire({
        icon: 'warning',
        title: 'Formulario incompleto',
        text: 'Revisa los campos obligatorios antes de continuar.',
        confirmButtonText: 'Entendido'
      });
      return;
    }

    if (this.editar && this.formCard.valid){
      this.isSubmitting = true;
      this.cardService.updateCard(this.formCard.getRawValue()).subscribe(
        {
          next:(data)=>{
            Swal.fire({
              icon: 'success',
              title: '¡Carta modificada!',
              text: 'La carta ha sido actualizada correctamente',
              confirmButtonText: 'Continuar'
            }).then(() => {
              this.router.navigate(['/card/list']);
            });
          },
          error:(err)=>{
            console.error('Error updating card', err);
            this.isSubmitting = false;
            Swal.fire({
              icon: 'error',
              title: 'Error al modificar',
              text: 'No se pudo actualizar la carta. Por favor, inténtalo de nuevo.',
              confirmButtonText: 'Entendido'
            });
          },
          complete:()=> {
            this.isSubmitting = false;
          }
        }
      )
    } else
    if (!this.editar && this.formCard.valid)
    {
      this.isSubmitting = true;
      this.cardService.addCard(this.formCard.getRawValue()).subscribe(
        {
          next:(data)=>{
            Swal.fire({
              icon: 'success',
              title: '¡Carta creada!',
              text: 'La carta ha sido agregada correctamente',
              confirmButtonText: 'Continuar'
            }).then(() => {
              this.router.navigate(['/card/list']);
            });
          },
          error:(err)=>{
            console.error('Error creating card', err);
            this.isSubmitting = false;
            Swal.fire({
              icon: 'error',
              title: 'Error al crear',
              text: 'No se pudo crear la carta. Por favor, inténtalo de nuevo.',
              confirmButtonText: 'Entendido'
            });
          },
          complete:()=> {
            this.isSubmitting = false;
          }
        }
      )
    }
  }

  addNewCollection() {
    const value = (this.newCollection.value ?? '').trim();
    if (!value) {
      return;
    }
    if (!this.collectionList.includes(value)) {
      this.collectionList.push(value);
    }
    this.formCard.patchValue({ collection: value });
    this.collection?.markAsDirty();
    this.collection?.markAsTouched();
    this.myNewCollection.reset();
  }

  deleteCard() {
    if (!this.id || this.isSubmitting) {
      return;
    }

    Swal.fire({
      title: '¿Estás seguro?',
      text: 'Esta acción no se puede deshacer',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#d33',
      cancelButtonColor: '#6c757d',
      confirmButtonText: 'Sí, eliminar',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {
        this.isSubmitting = true;
        this.cardService.deleteCard(this.id).subscribe({
          next: () => {
            Swal.fire({
              icon: 'success',
              title: '¡Carta eliminada!',
              text: 'La carta ha sido eliminada correctamente',
              confirmButtonText: 'Continuar'
            }).then(() => {
              this.router.navigate(['/card/list']);
            });
          },
          error: (err) => {
            console.error('Error deleting card', err);
            this.isSubmitting = false;
            Swal.fire({
              icon: 'error',
              title: 'Error al eliminar',
              text: 'No se pudo eliminar la carta. Por favor, inténtalo de nuevo.',
              confirmButtonText: 'Entendido'
            });
          },
          complete: () => {
            this.isSubmitting = false;
          }
        });
      }
    });
  }
}

﻿<div class="container-fluid edit-container">
  <style>
    /* apply same slightly lighter dark shade as file; remove rigid pure black override */
    .card-custom { background:#111111!important; color:#fff!important; }
    .card-custom * { color:#fff!important; }
  </style>
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10 col-xl-8 my-4">
      <div class="card card-custom">
        <div class="card-header text-center bg-mtg-blue text-white">
          <h2 class="mb-0">{{ editar ? 'Editar carta' : 'Nueva carta' }}</h2>
        </div>
        <div class="card-body">
          <form [formGroup]="formCard" (ngSubmit)="addCard()" class="card-form">
            <div class="row g-3">
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="name" class="form-label">Nombre de la carta</label>
                  <input type="text" formControlName="name" class="form-control" id="name" placeholder="Nombre">
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="collection" class="form-label">Colección</label>
                  <select class="form-select" id="collection" formControlName="collection">
                    <option value="" disabled>Selecciona una colección</option>
                    <option *ngFor="let collection of collectionList" [value]="collection">{{ collection }}</option>
                  </select>
                </div>
              </div>

              <div class="col-md-6">
                <div class="mb-3">
                  <label for="rarity" class="form-label">Rareza</label>
                  <input type="text" formControlName="rarity" class="form-control" id="rarity" placeholder="Rareza">
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="type" class="form-label">Tipo de carta</label>
                  <input type="text" formControlName="type" class="form-control" id="type" placeholder="Tipo">
                </div>
              </div>

              <div class="col-12">
                <div class="input-group mb-3" [formGroup]="myNewCollection">
                  <input type="text" formControlName="newCollection" class="form-control" placeholder="Nueva colección" id="newCollection">
                  <button class="btn btn-outline-primary" type="button" (click)="addNewCollection()">Agregar</button>
                </div>
              </div>

              <div class="col-md-6">
                <div class="mb-3">
                  <label for="price" class="form-label">Precio (€)</label>
                  <input type="number" formControlName="price" class="form-control" id="price" placeholder="0.00" min="0" step="0.01">
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="stock" class="form-label">Stock disponible</label>
                  <input type="number" formControlName="stock" class="form-control" id="stock" placeholder="0" min="0" step="1">
                </div>
              </div>

              <div class="col-md-6">
                <div class="mb-3">
                  <label for="language" class="form-label">Idioma</label>
                  <input type="text" formControlName="language" class="form-control" id="language" placeholder="Idioma">
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="condition" class="form-label">Estado</label>
                  <input type="text" formControlName="condition" class="form-control" id="condition" placeholder="Estado">
                </div>
              </div>

              <div class="col-12">
                <div class="mb-3">
                  <label for="imageUrl" class="form-label">URL de la imagen</label>
                  <input type="text" formControlName="imageUrl" class="form-control" id="imageUrl" placeholder="https://">
                </div>
              </div>
            </div>

            <div class="d-flex justify-content-between mt-4">
              <div class="d-flex gap-2">
                <button type="button" class="btn btn-outline-secondary btn-lg px-4" routerLink="/card/list">Cancelar</button>
                <button *ngIf="editar" type="button" class="btn btn-danger btn-lg px-4" (click)="deleteCard()" [disabled]="isSubmitting">Eliminar</button>
              </div>
              <button type="submit" class="btn btn-success btn-lg px-5" [disabled]="isSubmitting">
                {{editar? 'Actualizar' : 'Crear carta'}}
              </button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
